version: "3"

services:
  database:
    container_name: tmc2db
    image: mariadb
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MYSQL_DATABASE=tmcdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - 3306:3306
  web:
    image: tmc_web:v1
    build: .
    container_name: tmc_django_web
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/exam_django_web
    expose:
      - "8000"